name: 'Tiny Tapeout Custom GDS Action'
description: 'This action builds prepares a custom GDS project for submitting to Tiny Tapeout'
branding:
  color: purple
  icon: layers

inputs:
  top_module:
    description: 'The name of the top module (e.g. tt_um_example)'
    required: true
  gds_path:
    description: 'Path to the GDS file'
    required: true
  lef_path:
    description: 'Path to the LEF file'
    required: true
  verilog_path:
    description: 'Path to the verilog GL netlist (optional)'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Create commit_id.json
      shell: bash
      run: |
        mkdir -p tt_submission
        jq -n \
          --arg app "custom_gds action" \
          --arg repo "${{ github.server_url }}/${{ github.repository }}" \
          --arg commit "${{ github.sha }}" \
          --arg workflow_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          '{app: $app, repo: $repo, commit: $commit, workflow_url: $workflow_url}' \
          > tt_submission/commit_id.json

    - name: Copy GDS / LEF files to tt_submission
      shell: bash
      run: |
        cp ${{ inputs.gds_path }} tt_submission/${{ inputs.top_module }}.gds
        cp ${{ inputs.lef_path }} tt_submission/${{ inputs.top_module }}.lef
        
        touch tt_submission/${{ inputs.top_module }}.v
        if [ -n "${{ inputs.verilog_path }}" ]; then
          cp ${{ inputs.verilog_path }} tt_submission/${{ inputs.top_module }}.v
        fi

    - name: Publish tt_submission artifact
      uses: actions/upload-artifact@v3
      with:
        name: tt_submission
        path: |
          LICENSE
          docs/*
          tt_submission/*
